Update master_praizer-api.yml

diff --git a/.github/workflows/master_praizer-api.yml b/.github/workflows/master_praizer-api.yml
--- a/.github/workflows/master_praizer-api.yml
+++ b/.github/workflows/master_praizer-api.yml
@@ -24,9 +24,15 @@ jobs:
           
       - name: Download secrets JSON file
         run: |
-          curl -LO -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+          curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+          -o praizer-e6914-firebase-adminsdk-5c79t-df0dce4ff6.json \
           "https://api.github.com/repos/abhishek-dixit7/praizer-api-secrets/contents/praizer-e6914-firebase-adminsdk-5c79t-df0dce4ff6.json"
-          cat praizer-e6914-firebase-adminsdk-5c79t-df0dce4ff6.json
+          if [ -f "praizer-e6914-firebase-adminsdk-5c79t-df0dce4ff6.json" ]; then
+            cat praizer-e6914-firebase-adminsdk-5c79t-df0dce4ff6.json
+          else
+            echo "Failed to download the JSON file."
+            exit 1
+          fi
           
       - name: Set up dependency caching for faster builds
         uses: actions/cache@v3
